version: '3' 
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "${HOMEASSISTANT_DIR}:/config"
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    #network_mode: host
    networks:
      - mynet

  esphome:
    container_name: esphome
    image: esphome/esphome
    command: "dashboard --username $ESPHOME_USER --password $ESPHOME_PWD /config"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "${ESPHOME_DIR}:/config"
    ports:
      - 6123:6123
    privileged: true
    #network_mode: host
    networks:
      - mynet

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
        #network_mode: host
    volumes:
      - node-red-data:/data
    #network_mode: host
    networks:
      - mynet

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=$DUCKDNS_SUBDIR
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=false #optional
    volumes:
      - "${DUCKDNS_DIR}:/config"
    restart: unless-stopped
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx 
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 6052:6052
      - 1880:1880
    volumes:
      - "${NGINX_DIR}:/etc/nginx/nginx.conf"
      - "${SSL_DIR}:/ssl/"
    networks:
      - mynet

networks:
  mynet:

volumes:
  node-red-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $NODERED_DIR
